[General]
SyntaxVersion=2
BeginHotkey=118
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=b9faf204-a951-477a-b9dc-73d85eddd89b
Description=¥á¿ú
Enable=0
AutoRun=0
[Repeat]
Type=1
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
MoveTo 260, 598
LeftClick 1
Delay 50
KeyPress "Num 1", 1
KeyPress "Num 9", 1
KeyPress "Right", 1
KeyPress "Enter", 1
Delay 300
