[General]
SyntaxVersion=2
BeginHotkey=117
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=89e67ced-3633-4bec-97df-0d593c5aedd9
Description=接受GM任務
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
KeyPress "Space", 1
KeyPress "Enter", 1
Delay 200
KeyPress "Right", 1
KeyPress "Enter", 1
