[General]
SyntaxVersion=2
BeginHotkey=119
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=9132adba-6613-45f8-85e8-b26a70e25e5b
Description=空白鍵
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]
【功能說明】
飛翔吧公主 - 菲歐娜的願望
滿是60空白鍵
【使用說明】
<說明您的腳本應該怎麼去用>
舉例：按熱鍵一下，即可模擬點擊滑鼠左鍵一次。

[Script]
SetSimMode 0
'SetSimMode 2
KeyPress "Space", 100
