[General]
SyntaxVersion=2
BeginHotkey=122
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=b9d09d8f-3ce7-47d1-b614-22fd6d6777a8
Description=»â¼úÂ÷¶}
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
MoveTo 560, 620
LeftClick 1
Delay 300
KeyPress "Down", 2
KeyPress "Enter", 1
Delay 300
KeyPress "Right", 1
KeyPress "Enter", 1
