[General]
SyntaxVersion=2
BeginHotkey=121
BeginHotkeyMod=0
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=55c7d125-6f0b-4396-be07-7d99f80d450b
Description=我的腳本2
Enable=0
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]

[Script]
SayString "123"
KeyPress "Num 4", 1
KeyPress "Num 5", 1
KeyPress "Num 6", 1
UserVar Var1=0 "設置內容"
