[General]
SyntaxVersion=2
BeginHotkey=68
BeginHotkeyMod=2
PauseHotkey=0
PauseHotkeyMod=0
StopHotkey=123
StopHotkeyMod=0
RunOnce=1
EnableWindow=
MacroID=ff9c820d-c2b2-45f4-968c-eebeee0b2c53
Description=餵皿中x1
Enable=1
AutoRun=0
[Repeat]
Type=0
Number=1
[SetupUI]
Type=2
QUI=
[Relative]
SetupOCXFile=
[Comment]
【功能說明】
怪物掉落物放在左方地圖下
4*6的最右下角
培養皿放視窗右上角，餵食中間的
【使用說明】
<說明您的腳本應該怎麼去用>
舉例：按熱鍵一下，即可模擬點擊滑鼠左鍵一次。

[Script]
MoveTo 360, 560
LeftClick 1
Delay 200
MoveTo 1400, 620
LeftClick 1
